# Site settings
title: Eduardo Chamorro Docs
email: eduardochamorromartin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eduardo Chamorro Documentation
baseurl: "/docs/" # the subpath of your site, e.g. /blog/
url: "http://eduardochamorro.github.io/" # the base hostname & protocol for your site
twitter_username: username
github_username: EDUARDOCHAMORRO

# Build settings
markdown: kramdown #redcarpet
markdown_ext:  mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
